### ISSUE TITLE
Type classes and helper functions.

### ISSUE THREAD

**Issue by lemmih** [chessai/vector-circular#1]
Hi, love the library. It would be great if `CircularVector` had instances for `Generic`, `NFData` and `Traversable`. I'd also like to see `zipWith`, `zipWith3`, and `reverse`.

**Comment by chessai** [comment]
Cool! Definitely would accept PRs

**Comment by lemmih** [comment]
PR sent. Would like to make the API match Data.Vector.NonEmpty but that would take a bit more work.

**Comment by lemmih** [comment]
Nifty! Will you publish 0.2 (or 0.1.1) soon?

**Comment by chessai** [comment]
Yes, any functions you want in before then?

**Comment by lemmih** [comment]
I'm good with what we have now.

**Comment by chessai** [comment]
published, thanks for your help. please open issues/prs if you need anything else
