### ISSUE TITLE
Release a new version on Hackage?

### ISSUE THREAD

**Issue by noinia** [chessai/vector-circular#12]
As the topic suggests; this is one of the things blocking hgeometry from compiling on GHC 9.

**Comment by noinia** [comment]
Ping?

**Comment by chessai** [comment]
[hackage:vector-circular-0.1.4](https://hackage.haskell.org/package/vector-circular-0.1.4)
[git:vector-circular-0.1.4](https://github.com/chessai/vector-circular/tree/v0.1.4)

supports 9.0.x and 9.2.x

edit: thanks for the ping, i appreciate it!

**Comment by noinia** [comment]
Awesome! Thanks!
